services:
  app:
    build: .
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      MONGODB_URI: mongodb://mongodb:27017/httpz
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
